version: '3'
services:
  php:
    build: .
    volumes:
      - ./www:/var/www
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://nginx | grep -q 'works'"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
